### PR TITLE
created the 'waitingqueue,currentcustomer,and the chair count variable'

### PR DESCRIPTION
**Pull request by Akwasititus**
i've started working on the barbering shop project.
i created the;

1 'waitingqueue, 
2. currentcustome,
3.chair count

variables for the barbering shop project

### CODE REVIEW

**Comment by Linda-Boateng** [comment]
Titus your project structure is missing.
And also please don't create PRs for this.

**Comment by Linda-Boateng** [comment]
And donot merge unless I say so please

**Comment by Akwasititus** [comment]
you know there are two projects which one is missing 

the barbering shop anaa? the socia networking site?

**Comment by Linda-Boateng** [comment]
oh okay.
But you should follow the right architecture and structure in all projects you undertake.
The PRs should be made for every feature not every commit.

**Comment by Akwasititus** [comment]
ok

**Pull request merged**
